stages:
  - test
  - publish
  - notifications

before_script:
  # interferes with git repository handling in test
  - unset CI_REPOSITORY_URL
  - unset CI_BUILD_REF

tests:
  stage: test
  retry: 1
  tags:
    - gomason

  except:
    - master

  script:
    - gomason test -v -b ${CI_COMMIT_REF_NAME}

publish:
  stage: publish
  only:
    - master

  tags:
    - gomason

  script:
    - dbt secrets exec -p infra/deploy "gomason publish -vb $CI_COMMIT_REF_NAME"

# ----- Notifications
notify_slack_failure:
  stage: notifications
  when: on_failure
  dependencies: []
  before_script: []
  script:
    - /opt/scribd/bin/build_notifier.rb failed

notify_slack_success:
  stage: notifications
  when: on_success
  dependencies: []
  before_script: []
  script:
    - /opt/scribd/bin/build_notifier.rb success